# Generated by Django 6.1.1 on 2026-09-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
